In [105]:
!git config --global user.name "marta4cod"
!git config --global user.email "marta4cod@gmail.com"

In [106]:
token= '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'
username = 'marta4cod'
repo = 'NNAssessment1'

In [107]:
!git clone https://{token}@github.com/{username}/{repo}

Cloning into 'NNAssessment1'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 18 (delta 6), reused 4 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (18/18), 40.43 KiB | 726.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.


In [108]:
%cd {repo}
%ls

/content/NNAssessment1/NNAssessment1/NNAssessment1
Code  NNAs1.ipynb  README.md  student_lifestyle_dataset.csv


In [109]:
#!mv /content/student_lifestyle_dataset.csv /content/NNAssessment1/NNAssessment1/NNAssessment1

In [110]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [111]:
!mv /content/drive/MyDrive/Colab Notebooks/NNAs1.ipynb /content/NNAssessment1/NNAssessment1/NNAssessment1
!git add /content/drive/MyDrive/Colab Notebooks/NNAs1.ipynb
!git commit -a -m "Added dataset to the respiratory"
!git push origin main

mv: cannot stat '/content/drive/MyDrive/Colab': No such file or directory
mv: cannot stat 'Notebooks/NNAs1.ipynb': No such file or directory
fatal: Invalid path '/content/drive': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Password for 'https://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@github.com': No such device or address


In [112]:
import numpy as np
import pandas as pd
data = pd.read_csv('/content/NNAssessment1/student_lifestyle_dataset.csv')

In [113]:
data.shape

(2000, 8)

In [114]:
data.head()

Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8   
1           2                  5.3                            3.5   
2           3                  5.1                            3.9   
3           4                  6.5                            2.1   
4           5                  8.1                            0.6   

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8   
1                  8.0                   4.2                              3.0   
2                  9.2                   1.2                              4.6   
3                  7.2                   1.7                              6.5   
4                  6.5                   2.2                              6.6   

    GPA Stress_Level  
0  2.99     Moderate  
1  2.75          Low  
2  2.67          Low  
3  2.88     Moderate  
4  3.51         High

In [115]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   Student_ID                       2000 non-null   int64  
 1   Study_Hours_Per_Day              2000 non-null   float64
 2   Extracurricular_Hours_Per_Day    2000 non-null   float64
 3   Sleep_Hours_Per_Day              2000 non-null   float64
 4   Social_Hours_Per_Day             2000 non-null   float64
 5   Physical_Activity_Hours_Per_Day  2000 non-null   float64
 6   GPA                              2000 non-null   float64
 7   Stress_Level                     2000 non-null   object 
dtypes: float64(6), int64(1), object(1)
memory usage: 125.1+ KB


In [116]:
data.describe()

Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
count  2000.000000          2000.000000                    2000.000000   
mean   1000.500000             7.475800                       1.990100   
std     577.494589             1.423888                       1.155855   
min       1.000000             5.000000                       0.000000   
25%     500.750000             6.300000                       1.000000   
50%    1000.500000             7.400000                       2.000000   
75%    1500.250000             8.700000                       3.000000   
max    2000.000000            10.000000                       4.000000   

       Sleep_Hours_Per_Day  Social_Hours_Per_Day  \
count          2000.000000           2000.000000   
mean              7.501250              2.704550   
std               1.460949              1.688514   
min               5.000000              0.000000   
25%               6.200000              1.200000   
50%               7.500000              2.600000   
75%               8.800000              4.100000   
max              10.000000              6.000000   

       Physical_Activity_Hours_Per_Day          GPA  
count                       2000.00000  2000.000000  
mean                           4.32830     3.115960  
std                            2.51411     0.298674  
min                            0.00000     2.240000  
25%                            2.40000     2.900000  
50%                            4.10000     3.110000  
75%                            6.10000     3.330000  
max                           13.00000     4.000000

In [117]:
data.isnull().sum()

Student_ID                         0
Study_Hours_Per_Day                0
Extracurricular_Hours_Per_Day      0
Sleep_Hours_Per_Day                0
Social_Hours_Per_Day               0
Physical_Activity_Hours_Per_Day    0
GPA                                0
Stress_Level                       0
dtype: int64

In [118]:
data['Stress_Level'].value_counts()

Stress_Level
High        1029
Moderate     674
Low          297
Name: count, dtype: int64

The data points in colmn 'Stress_level' are recorded as characters. Whethever we decide to create Regresssion or Classification model we need to convert those values into numeric.


In [119]:
#replace words (objects) to numbers
data['Stress_Level'] = data['Stress_Level'].replace({
    'Low': 0,
    'Moderate': 1,
    'High': 2
})

# Convert to integer type
data['Stress_Level'] = data['Stress_Level'].astype(int)


<ipython-input-119-0cf5889a3f81>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Stress_Level'] = data['Stress_Level'].replace({


In [120]:
data.head()

Student_ID  Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  \
0           1                  6.9                            3.8   
1           2                  5.3                            3.5   
2           3                  5.1                            3.9   
3           4                  6.5                            2.1   
4           5                  8.1                            0.6   

   Sleep_Hours_Per_Day  Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day  \
0                  8.7                   2.8                              1.8   
1                  8.0                   4.2                              3.0   
2                  9.2                   1.2                              4.6   
3                  7.2                   1.7                              6.5   
4                  6.5                   2.2                              6.6   

    GPA  Stress_Level  
0  2.99             1  
1  2.75             0  
2  2.67             0  
3  2.88             1  
4  3.51             2

For the regression model we will be trying to calculate predicted GPA. For classification model we will attemt to group students by their stress level. We will check now if there is no unique values for those 2 columns of potential predition.

In [121]:
print(data['GPA'].unique())
print(data['Stress_Level'].unique)

[2.99 2.75 2.67 2.88 3.51 2.85 3.08 3.2  2.82 2.76 3.43 2.97 2.87 3.4
 3.36 3.19 3.16 2.93 2.9  3.34 3.21 2.68 3.29 2.64 2.95 2.79 3.25 3.05
 3.26 2.47 3.24 3.62 3.12 2.58 3.03 2.61 3.48 3.07 2.81 3.49 3.55 2.6
 3.09 3.47 3.18 4.   3.33 3.11 3.1  2.39 3.39 2.52 2.8  3.67 3.27 3.06
 3.38 3.15 2.69 3.54 3.37 3.58 2.89 3.44 3.35 2.62 2.86 3.78 2.96 3.45
 3.41 3.22 2.98 3.3  3.28 2.7  3.14 2.73 3.64 2.94 3.57 2.72 2.45 3.13
 3.59 3.65 3.42 3.02 2.38 2.71 2.59 2.46 3.5  2.78 3.52 3.17 2.66 2.77
 3.77 3.01 2.84 3.23 3.32 3.8  3.84 3.68 2.92 3.61 3.31 2.91 3.56 2.5
 2.65 3.66 3.46 2.83 3.   3.04 2.25 3.6  3.53 3.63 2.28 2.31 3.75 3.81
 3.69 3.74 2.74 2.63 2.55 2.49 2.44 2.54 3.79 2.48 2.53 2.57 2.41 3.71
 3.76 2.24 3.92 2.3  3.72 3.73 3.93 2.56 3.87 2.42 3.91 2.51 3.85 3.9
 3.7  2.35 3.82 3.86]
<bound method Series.unique of 0       1
1       0
2       0
3       1
4       2
       ..
1995    1
1996    1
1997    1
1998    2
1999    2
Name: Stress_Level, Length: 2000, dtype: int64>


We start with regression model.

In [122]:
data_reg=data.drop(columns=['Student_ID']) # we do not need Student_ID column
print(data_reg.head())

   Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  Sleep_Hours_Per_Day  \
0                  6.9                            3.8                  8.7   
1                  5.3                            3.5                  8.0   
2                  5.1                            3.9                  9.2   
3                  6.5                            2.1                  7.2   
4                  8.1                            0.6                  6.5   

   Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day   GPA  Stress_Level  
0                   2.8                              1.8  2.99             1  
1                   4.2                              3.0  2.75             0  
2                   1.2                              4.6  2.67             0  
3                   1.7                              6.5  2.88             1  
4                   2.2                              6.6  3.51             2  


In [123]:
from sklearn.model_selection import train_test_split


In [124]:
X= data_reg.drop(columns=['GPA'])
y=data_reg['GPA']

In [125]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,
                                                    random_state=35)

In [126]:
# Standardize the feature data (scaling it to mean 0 and variance 1)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [127]:
# Build the feedforward neural network (MLP)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import time


model = Sequential([  # Define input shape using Input layer
    Dense(32, activation='relu', input_dim=X_train.shape[1]),      # Hidden layer with 32 neurons
    Dense(16, activation='relu'),      # Hidden layer with 16 neurons
    Dense(1, activation='linear')      # Output layer for regression
])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [128]:
from sklearn.metrics import mean_squared_error
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_squared_error'])

In [129]:
# Train the model
start_time=time.time()
history=model.fit(X_train, y_train, epochs=50, batch_size=10, verbose=1)
end_time=time.time()

Epoch 1/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3518 - mean_squared_error: 7.3518
Epoch 2/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.4836 - mean_squared_error: 0.4836
Epoch 3/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3099 - mean_squared_error: 0.3099
Epoch 4/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2026 - mean_squared_error: 0.2026
Epoch 5/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1574 - mean_squared_error: 0.1574
Epoch 6/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1147 - mean_squared_error: 0.1147
Epoch 7/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0924 - mean_squared_error: 0.0924
Epoch 8/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0738 - mean_squared_error: 0.0738
Epoch 9/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0635 - mean_squared_error: 0.0635
Epoch 10/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0580 - mean_squared_error: 0.0580
Epoch 11/50
160/160 ━━━━━━━━━━━━━━━━━━━

In [130]:
# Predict on test data
y_pred = model.predict(X_test).flatten()  # Flatten to 1D array for comparison

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 


In [131]:
print(X_test[:10])
print(y_pred[:10])

[[-1.61794962 -1.63336924  0.94489145 -1.14503918  1.8941261  -1.89932358]
 [-0.55580922  1.64501613  0.46361516  0.93421742 -1.34861498 -0.51358818]
 [ 1.3560435  -0.94318284 -1.46148997  0.10251478  0.45290784  0.87214722]
 [ 0.78956862 -0.16672315 -0.84270618 -0.96681719  0.77317856  0.87214722]
 [-0.13095306  0.00582345 -1.46148997  0.81540275  0.37284016  0.87214722]
 [ 0.08147502 -1.46082264 -0.43018365  1.64710539 -0.22766745 -0.51358818]
 [-1.68875898  1.12737634  1.63242899 -1.14503918  0.25273864 -1.89932358]
 [-0.83904666 -1.28827604 -0.01766112  0.45895876  0.77317856 -0.51358818]
 [-1.19309346 -0.33926975  1.56367524 -0.72918786  0.412874   -1.89932358]
 [-0.90985602 -1.71964254 -0.91145993 -1.14503918  2.61473522 -0.51358818]]
[2.6868894 3.013093  3.5070794 3.2425618 3.1081262 3.0662756 2.485716
 2.993512  2.589644  2.887309 ]


In [132]:
# Compile the model for regression
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_squared_error'])

In [133]:
# Evaluate the model on test data using Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 0.04869743624622606


Creating Classification model

In [134]:
data_clas=data.drop(columns=['Student_ID']) # we do not need Student_ID column
print(data_reg.head())

# Define X and y
Xc = data_clas.iloc[:, :-1]  # All columns except the last one (features)
yc= data_clas.iloc[:, -1]   # The last column (output)

# Split the data into training and testing sets
Xc_train, Xc_test, yc_train, yc_test = train_test_split(Xc, yc, test_size=0.2, random_state=42)


   Study_Hours_Per_Day  Extracurricular_Hours_Per_Day  Sleep_Hours_Per_Day  \
0                  6.9                            3.8                  8.7   
1                  5.3                            3.5                  8.0   
2                  5.1                            3.9                  9.2   
3                  6.5                            2.1                  7.2   
4                  8.1                            0.6                  6.5   

   Social_Hours_Per_Day  Physical_Activity_Hours_Per_Day   GPA  Stress_Level  
0                   2.8                              1.8  2.99             1  
1                   4.2                              3.0  2.75             0  
2                   1.2                              4.6  2.67             0  
3                   1.7                              6.5  2.88             1  
4                   2.2                              6.6  3.51             2  


In [135]:
# Standardize the feature data (scaling it to mean 0 and variance 1)
scaler = StandardScaler()
Xc_train = scaler.fit_transform(Xc_train)
Xc_test = scaler.transform(Xc_test)
, input_dim=Xc_train.shape[1]

'input_dim=Xc_train.shape[1]'

In [136]:
# Build the feedforward neural network (MLP)
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=Xc_train.shape[1]))  # Hidden layer with 32 neurons
model.add(Dense(16, activation='relu'))  # Hidden layer with 16 neurons
model.add(Dense(3, activation='softmax'))  # Output layer with 1 neuron for binary classificationm

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [137]:
print("Xc_train shape:", Xc_train.shape)
print("yc_train shape:", yc_train.shape)
print("yc_train unique values:", np.unique(yc_train))



Xc_train shape: (1600, 6)
yc_train shape: (1600,)
yc_train unique values: [0 1 2]


In [138]:
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score


# Compile the model - constuct neural network, define loss function
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
# Train the model
model.fit(Xc_train, yc_train, epochs=50, batch_size=10, verbose=1)

Epoch 1/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.5527 - loss: 0.9556
Epoch 2/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7643 - loss: 0.5410
Epoch 3/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8513 - loss: 0.4010
Epoch 4/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9022 - loss: 0.2966
Epoch 5/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9166 - loss: 0.2375
Epoch 6/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9376 - loss: 0.1950
Epoch 7/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9391 - loss: 0.1789
Epoch 8/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9423 - loss: 0.1606
Epoch 9/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9619 - loss: 0.1313
Epoch 10/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9506 - loss: 0.1419
Epoch 11/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9598 - loss: 0.1163
Epoch 12/50
160/160 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [141]:
# Import classification_report
from sklearn.metrics import classification_report

# Evaluate the model on test data
yc_pred_prob = model.predict(Xc_test)
yc_pred = np.argmax(yc_pred_prob, axis=1)  # Convert probabilities to binary output (0 or 1), conditional statement

# Evaluate the model
accuracy = accuracy_score(yc_test, yc_pred)
report = classification_report(yc_test, yc_pred)

# Output results
print(f'Accuracy: {accuracy}')
print('Classification Report:')
print(report)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
Accuracy: 0.9675
Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.97      0.94        67
           1       0.98      0.94      0.96       127
           2       0.98      0.99      0.98       206

    accuracy                           0.97       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.97      0.97      0.97       400

